server:
  port: 8888
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
# spring配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/tulingshop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1h
      cache-null-values: true
      use-key-prefix: true
  mvc:
    format:
      date: yyyy-MM-dd HH:ss:mm
# mybatis配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto # id生成的策略

# 设置日志级别
logging:
  level:
    com.aojiaodage: debug

# 可查看项目依赖情况
# debug: true